#!/bin/bash
set -euo pipefail
set -o errexit
set -o errtrace

if [ "x$SFTP_USER" == "x" ]
then
  echo Please set \$SFTP_USER
  exit 1
fi

if [ "x$SFTP_PASS" == "x" ]
then
  echo Please set \$SFTP_PASS
  exit 1
fi


echo "Creating user ${SFTP_USER}"
adduser -D ${SFTP_USER}
echo "${SFTP_USER}:${SFTP_PASS}" | chpasswd

export AWSACCESSKEYID=$AWS_ACCESS_KEY
export AWSSECRETACCESSKEY=$AWS_SECRET_KEY

mkdir -p /home/$SFTP_USER
chown root:root /home/$SFTP_USER
chmod 745 /home/$SFTP_USER

mkdir -p /home/$SFTP_USER/s3
s3fs $S3_BUCKET /home/$SFTP_USER/s3  -o nosuid,nonempty,nodev,allow_other,retries=5

echo "StrictModes no
PasswordAuthentication yes
AllowUsers $SFTP_USER
AuthorizedKeysFile /keys/$SFTP_USER
UseDNS no
Subsystem sftp internal-sftp
Match User $SFTP_USER
ChrootDirectory /home/$SFTP_USER
ForceCommand internal-sftp
AllowTCPForwarding no
X11Forwarding no
" > /etc/ssh/sshd_config

if [ "x$SFTP_PUBLIC_KEY" != "x" ]
then
  mkdir -p /keys
  echo $SFTP_PUBLIC_KEY > /keys/$SFTP_USER
  chown $SFTP_USER:$SFTP_USER /keys/$SFTP_USER
  chmod 0444 /keys/$SFTP_USER
fi


if [ ! -f /etc/ssh/ssh_host_rsa_key ]
then
    ssh-keygen -t rsa -b 2048 -N '' -f /etc/ssh/ssh_host_rsa_key
    ssh-keygen -t dsa -N '' -f /etc/ssh/ssh_host_dsa_key
    ssh-keygen -t ecdsa -N '' -f /etc/ssh/ssh_host_ecdsa_key
    ssh-keygen -t ed25519 -N '' -f /etc/ssh/ssh_host_ed25519_key || true
fi

echo "SFTP credentials: $SFTP_USER:$SFTP_PASS"
echo "S3 Bucket: $S3_BUCKET"
echo "Ready to accept connections..."
exec $@
